version: "3"
services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
 
  app:
    # replace imageName with your image name (block in your case)
    build: .
    ports:
      - 4000:5000 # Replace the port of your application here if used
    environment:
      - DB_URI=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
 
volumes:
  mongo_db: {}
 